# Generated by Django 6.0.2 on 2026-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam',
            field=models.CharField(choices=[('FIRST_MID', 'First Mid Term'), ('FIRST_TERM', 'First Term'), ('SECOND_MID', 'Second Mid Term'), ('ANNUAL', 'Annual Exam')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
