# Generated by Django 6.0.2 on 2026-02-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SchoolAdmin', '0006_student_user'),
        ('Teacher', '0004_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.student')),
            ],
        ),
    ]
