# Generated by Django 6.0.2 on 2026-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_studentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
