# Generated by Django 6.0.2 on 2026-02-16 13:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0002_schoolclass_division_subject_teacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('date_of_joining', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='SchoolAdmin.division')),
            ],
        ),
    ]
